spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  sql:
    init:
      encoding: UTF-8
      mode: always
  h2:
    console:
      enabled: true
      path: /h2-console
